import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

export type SidebarEntry =
  | string
  | {
      label?: string;
      slug?: string;
      link?: string;
      items?: SidebarEntry[];
      autogenerate?: { directory: string };
    };

interface Page {
  id: string;
  title: string;
  description?: string;
  order?: number;
}

/** URL of the Markdown copy of a page, served by `src/pages/[...slug].md.ts`. */
export function markdownUrl(site: string, id: string): string {
  return new URL(`${id}.md`, site.endsWith('/') ? site : `${site}/`).href;
}

/**
 * Builds the `llms.txt` page index: one `##` section per top-level sidebar
 * group, linking every page's Markdown copy with its description. Pages no
 * group reaches are listed under "Other pages" so none go missing.
 */
export function buildPageIndex(
  sidebar: SidebarEntry[],
  { contentDir, site }: { contentDir: string; site: string }
): string {
  const pages = readPages(contentDir);
  const listed = new Set<string>();
  const sections: string[] = [];

  const collect = (entry: SidebarEntry): Page[] => {
    if (typeof entry === 'string') return pageById(pages, entry);
    if (entry.slug !== undefined) return pageById(pages, entry.slug);
    if (entry.autogenerate) return autogenerated(pages, entry.autogenerate.directory);
    return (entry.items ?? []).flatMap(collect);
  };

  for (const entry of sidebar) {
    if (typeof entry === 'string' || !(entry.items || entry.autogenerate) || !entry.label) continue;
    const found = collect(entry);
    for (const page of found) listed.add(page.id);
    sections.push(renderSection(entry.label, found, site));
  }

  const unlisted = [...pages.values()].filter((page) => !listed.has(page.id));
  if (unlisted.length > 0) sections.push(renderSection('Other pages', unlisted, site));
  return sections.join('\n\n');
}

function renderSection(label: string, pages: Page[], site: string): string {
  const lines = pages.map((page) => {
    const link = `- [${page.title}](${markdownUrl(site, page.id)})`;
    return page.description ? `${link}: ${page.description}` : link;
  });
  return [`## ${label}`, '', ...lines].join('\n');
}

function pageById(pages: Map<string, Page>, slug: string): Page[] {
  const page = pages.get(slug.replace(/^\/|\/$/g, '') || 'index');
  if (!page) throw new Error(`llms.txt page index: sidebar slug "${slug}" has no page`);
  return [page];
}

function autogenerated(pages: Map<string, Page>, directory: string): Page[] {
  const prefix = directory.replace(/^\/|\/$/g, '');
  return [...pages.values()]
    .filter((page) => page.id === prefix || page.id.startsWith(`${prefix}/`))
    .sort(
      (a, b) =>
        (a.order ?? Number.POSITIVE_INFINITY) - (b.order ?? Number.POSITIVE_INFINITY) ||
        a.id.localeCompare(b.id)
    );
}

function readPages(contentDir: string): Map<string, Page> {
  const pages = new Map<string, Page>();
  for (const file of readdirSync(contentDir, { recursive: true, encoding: 'utf-8' }).sort()) {
    if (!/\.mdx?$/.test(file)) continue;
    const id = file
      .replaceAll('\\', '/')
      .replace(/\.mdx?$/, '')
      .replace(/\/index$/, '');
    const frontmatter = readFileSync(join(contentDir, file), 'utf-8').match(
      /^---\r?\n([\s\S]*?)\r?\n---/
    )?.[1];
    if (frontmatter === undefined) throw new Error(`llms.txt page index: ${file} has no frontmatter`);
    if (/^draft:[ \t]*true[ \t]*$/m.test(frontmatter)) continue;
    if (/^slug:/m.test(frontmatter)) {
      throw new Error(`llms.txt page index: ${file} overrides its slug, which the index can't follow`);
    }
    const title = field(frontmatter, 'title', file);
    if (!title) throw new Error(`llms.txt page index: ${file} has no title`);
    const order = frontmatter.match(/^sidebar:[ \t]*\r?\n(?:[ \t]+.*\r?\n)*?[ \t]+order:[ \t]*(-?\d+)/m)?.[1];
    pages.set(id, {
      id,
      title,
      description: field(frontmatter, 'description', file),
      order: order === undefined ? undefined : Number(order),
    });
  }
  return pages;
}

/**
 * Reads a top-level, single-line frontmatter value, unquoting it if needed.
 * A full YAML parser would need a docs dependency, which the root test run
 * doesn't install, so multi-line values fail the build instead.
 */
function field(frontmatter: string, key: string, file: string): string | undefined {
  const line = frontmatter.match(new RegExp(`^${key}:(.*)$`, 'm'));
  if (!line) return undefined;
  const raw = line[1]!.trim();
  if (!raw || /^[|>]/.test(raw)) {
    throw new Error(`llms.txt page index: ${file} needs a single-line ${key}`);
  }
  const quoted = raw.match(/^(['"])(.*)\1$/);
  if (!quoted) return raw;
  return quoted[1] === "'" ? quoted[2]!.replaceAll("''", "'") : quoted[2]!.replaceAll('\\"', '"');
}
