import { afterEach, beforeEach, describe, expect, it } from 'bun:test';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { buildPageIndex, markdownUrl } from '../../docs/src/llms-page-index.ts';

const site = 'https://docs.example.com';

describe('llms.txt page index', () => {
  let contentDir: string;

  const page = (path: string, frontmatter: string) => {
    const file = join(contentDir, path);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, `---\n${frontmatter}\n---\n\nBody.\n`);
  };

  beforeEach(() => {
    contentDir = mkdtempSync(join(tmpdir(), 'bb-llms-index-'));
  });

  afterEach(() => {
    rmSync(contentDir, { recursive: true, force: true });
  });

  it('should list sidebar groups as sections of Markdown page links', () => {
    page('getting-started/quickstart.mdx', 'title: Quick Start\ndescription: Get going');
    page('reference/json-output.mdx', 'title: JSON Output');

    const index = buildPageIndex(
      [
        { label: 'Getting Started', items: [{ label: 'Quick', slug: 'getting-started/quickstart' }] },
        { label: 'Reference', items: ['reference/json-output'] },
      ],
      { contentDir, site }
    );

    expect(index).toBe(
      [
        '## Getting Started',
        '',
        '- [Quick Start](https://docs.example.com/getting-started/quickstart.md): Get going',
        '',
        '## Reference',
        '',
        '- [JSON Output](https://docs.example.com/reference/json-output.md)',
      ].join('\n')
    );
  });

  it('should flatten nested groups and order autogenerated pages by sidebar order', () => {
    page('commands/repo.mdx', 'title: Repo');
    page('commands/pr/index.mdx', 'title: PR\nsidebar:\n  order: 1');
    page('commands/pr/merge.mdx', 'title: Merge\nsidebar:\n  order: 3');
    page('commands/pr/create.mdx', 'title: Create\nsidebar:\n  order: 2');

    const index = buildPageIndex(
      [
        {
          label: 'Commands',
          items: [
            { label: 'Repo', items: [{ label: 'Basics', slug: 'commands/repo' }] },
            { label: 'PR', items: [{ autogenerate: { directory: 'commands/pr' } }] },
          ],
        },
      ],
      { contentDir, site }
    );

    expect(index.split('\n').filter((line) => line.startsWith('- '))).toEqual([
      `- [Repo](${site}/commands/repo.md)`,
      `- [PR](${site}/commands/pr.md)`,
      `- [Create](${site}/commands/pr/create.md)`,
      `- [Merge](${site}/commands/pr/merge.md)`,
    ]);
  });

  it('should list pages the sidebar does not reach under Other pages', () => {
    page('index.mdx', 'title: Home\ndescription: Landing page');
    page('guides/scripting.mdx', 'title: Scripting');

    const index = buildPageIndex([{ label: 'Guides', items: ['guides/scripting'] }], {
      contentDir,
      site,
    });

    expect(index).toEndWith(
      `## Other pages\n\n- [Home](${site}/index.md): Landing page`
    );
  });

  it('should unquote frontmatter values and skip draft pages', () => {
    page('a.md', `title: 'It''s quoted'\ndescription: "Say \\"hi\\""`);
    page('draft.mdx', 'title: Draft\ndraft: true');

    const index = buildPageIndex([], { contentDir, site });

    expect(index).toBe(`## Other pages\n\n- [It's quoted](${site}/a.md): Say "hi"`);
  });

  it('should fail the build on frontmatter the index cannot read', () => {
    page('multi.mdx', 'title: Multi\ndescription: >-\n  folded text');
    expect(() => buildPageIndex([], { contentDir, site })).toThrow(
      'multi.mdx needs a single-line description'
    );

    rmSync(join(contentDir, 'multi.mdx'));
    page('moved.mdx', 'title: Moved\nslug: elsewhere');
    expect(() => buildPageIndex([], { contentDir, site })).toThrow('moved.mdx overrides its slug');
  });

  it('should fail the build when a sidebar slug has no page', () => {
    expect(() =>
      buildPageIndex([{ label: 'Gone', items: ['missing/page'] }], { contentDir, site })
    ).toThrow('sidebar slug "missing/page" has no page');
  });

  it('should build Markdown URLs with or without a trailing slash on the site', () => {
    expect(markdownUrl(site, 'commands/pr')).toBe(`${site}/commands/pr.md`);
    expect(markdownUrl(`${site}/`, 'index')).toBe(`${site}/index.md`);
  });
});
